services:
  db:
    image: postgres:16
    container_name: hackathon_db
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: hackathon_web
    depends_on:
      - db
    environment:
      DB_NAME: hackathon_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"

volumes:
  postgres_data:
